// Auto-generated by scripts/generate-categories.js
// DO NOT EDIT THIS FILE DIRECTLY

export const categories = [
  {
    "name": "Camera & Controls",
    "color": "red",
    "routes": [
      {
        "path": "coord",
        "title": "Coordinates",
        "thumbnail": "/thumbnails/coord.jpg"
      },
      {
        "path": "orbit-pivot",
        "title": "Orbit Pivot",
        "thumbnail": "/thumbnails/orbit-pivot.jpg"
      },
      {
        "path": "orbit-pivot/offset",
        "title": "Orbit Pivot Offset",
        "thumbnail": "/thumbnails/orbit-pivot-offset.jpg"
      },
      {
        "path": "view-offset",
        "title": "View Offset",
        "thumbnail": "/thumbnails/view-offset.jpg"
      }
    ]
  },
  {
    "name": "Geometry",
    "color": "green",
    "routes": [
      {
        "path": "deoverlap",
        "title": "Deoverlap",
        "thumbnail": "/thumbnails/deoverlap.jpg"
      },
      {
        "path": "extruded",
        "title": "Extruded",
        "thumbnail": "/thumbnails/extruded.jpg"
      },
      {
        "path": "max-inscribed",
        "title": "Max Inscribed",
        "thumbnail": "/thumbnails/max-inscribed.jpg"
      },
      {
        "path": "pointcloud",
        "title": "Point Cloud",
        "thumbnail": "/thumbnails/pointcloud.jpg"
      },
      {
        "path": "spine",
        "title": "Spine",
        "thumbnail": "/thumbnails/spine.jpg"
      },
      {
        "path": "structural-geology",
        "title": "Structural Geology",
        "thumbnail": "/thumbnails/structural-geology.jpg"
      }
    ]
  },
  {
    "name": "Scene & Rendering",
    "color": "blue",
    "routes": [
      {
        "path": "batched-geometry",
        "title": "Batched Geometry",
        "thumbnail": "/thumbnails/batched-geometry.jpg"
      },
      {
        "path": "fps",
        "title": "FPS",
        "thumbnail": "/thumbnails/fps.jpg"
      },
      {
        "path": "instancedmesh",
        "title": "Instanced Mesh",
        "thumbnail": "/thumbnails/instancedmesh.jpg"
      },
      {
        "path": "scene",
        "title": "Scene",
        "thumbnail": "/thumbnails/scene.jpg"
      },
      {
        "path": "textures",
        "title": "Textures",
        "thumbnail": "/thumbnails/textures.jpg"
      }
    ]
  },
  {
    "name": "Shaders & WebGL",
    "color": "yellow",
    "routes": [
      {
        "path": "shader-course/functions",
        "title": "Shader Functions",
        "thumbnail": "/thumbnails/shader-course-functions.jpg"
      },
      {
        "path": "shader-course/textures",
        "title": "Shader Textures",
        "thumbnail": "/thumbnails/shader-course-textures.jpg"
      },
      {
        "path": "webgl",
        "title": "WebGL",
        "thumbnail": "/thumbnails/webgl.jpg"
      }
    ]
  },
  {
    "name": "Visual Effects",
    "color": "purple",
    "routes": [
      {
        "path": "blending",
        "title": "Blending",
        "thumbnail": "/thumbnails/blending.jpg"
      },
      {
        "path": "fan",
        "title": "Fan",
        "thumbnail": "/thumbnails/fan.jpg"
      },
      {
        "path": "sdf-font",
        "title": "SDF Font",
        "thumbnail": "/thumbnails/sdf-font.jpg"
      },
      {
        "path": "blending/transparency",
        "title": "Transparency",
        "thumbnail": "/thumbnails/blending-transparency.jpg"
      }
    ]
  }
];
