// Auto-generated by scripts/generate-categories.js
// DO NOT EDIT THIS FILE DIRECTLY

export const categories = [
  {
    "name": "Camera & Controls",
    "color": "red",
    "routes": [
      {
        "path": "coord",
        "title": "Coordinates"
      },
      {
        "path": "orbit-pivot",
        "title": "Orbit Pivot"
      },
      {
        "path": "orbit-pivot/offset",
        "title": "Orbit Pivot Offset"
      },
      {
        "path": "view-offset",
        "title": "View Offset"
      }
    ]
  },
  {
    "name": "Geometry",
    "color": "green",
    "routes": [
      {
        "path": "deoverlap",
        "title": "Deoverlap"
      },
      {
        "path": "extruded",
        "title": "Extruded"
      },
      {
        "path": "max-inscribed",
        "title": "Max Inscribed"
      },
      {
        "path": "pointcloud",
        "title": "Point Cloud"
      },
      {
        "path": "spine",
        "title": "Spine"
      },
      {
        "path": "structural-geology",
        "title": "Structural Geology"
      }
    ]
  },
  {
    "name": "Scene & Rendering",
    "color": "blue",
    "routes": [
      {
        "path": "batched-geometry",
        "title": "Batched Geometry"
      },
      {
        "path": "fps",
        "title": "FPS"
      },
      {
        "path": "instancedmesh",
        "title": "Instanced Mesh"
      },
      {
        "path": "scene",
        "title": "Scene"
      },
      {
        "path": "textures",
        "title": "Textures"
      }
    ]
  },
  {
    "name": "Shaders & WebGL",
    "color": "yellow",
    "routes": [
      {
        "path": "shader-course/functions",
        "title": "Shader Functions"
      },
      {
        "path": "shader-course/textures",
        "title": "Shader Textures"
      },
      {
        "path": "webgl",
        "title": "WebGL"
      }
    ]
  },
  {
    "name": "Visual Effects",
    "color": "purple",
    "routes": [
      {
        "path": "blending",
        "title": "Blending"
      },
      {
        "path": "fan",
        "title": "Fan"
      },
      {
        "path": "sdf-font",
        "title": "SDF Font"
      },
      {
        "path": "blending/transparency",
        "title": "Transparency"
      }
    ]
  }
];
